name: ESP-IDF CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install ESP-IDF manually
      run: |
        git clone -b v5.1 --recursive https://github.com/espressif/esp-idf.git
        ./esp-idf/install.sh esp32
        . ./esp-idf/export.sh

    - name: Build firmware
      run: idf.py build
